version: "3.7"
services:
    sam:
        container_name: "lambda-sam"
        build: 
            context: docker/sam
            dockerfile: Dockerfile
        environment:
            - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
            - "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
            - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
        volumes:
            - "./project:/project:delegated"
        working_dir: /project
